name: deploy workflow
on: [workflow_dispatch, push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: build job
        run: echo "printing greeting"
      - name: cloning code from the repository
        uses: actions/checkout@v3