    name: deploy workflow
    on: [workflow_dispatch, push]
    jobs:
      first-job:
        runs-on: ubuntu-latest
        steps:
          - name: build job
            run: echo "printing greeting"
          - name: Cloning Code From The Repository
            uses: actions/checkout@v3
          - name: Install Dependencies
            uses: actions/setup-node@v2
            with:
              node-version: 14
      plugin-job:
        runs-on: ubuntu-latest
        steps:
          - name: Cloning Code From The Repository
            uses: actions/checkout@v3
          - name: Install Dependencies
            uses: actions/setup-node@v2
            with:
                node-version: 18
          - name: Install Dev Plugin Dependencies
            run: npm run dev